trigger:
- '*'

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    sudo apt-get update
    sudo apt-get install -y build-essential
    sudo apt-get install -y cmake
    sudo apt-get install -y libgtest-dev
    cd /usr/src/gtest
    sudo cmake CMakeLists.txt
    sudo make
    sudo cp *.a /usr/lib
  displayName: 'Install GTest'

- script: |
    make clean
    make
  displayName: 'Build C++ Code'

- script: |
    ./run_tests.sh
  displayName: 'Run Unit Tests'

